USE DATABASE TCC_ASSIGNMENT;
USE SCHEMA SALES;

TRUNCATE TABLE IF EXISTS STG_PRODUCTS;
COPY INTO STG_PRODUCTS FROM @s3_tcc_stage/products.csv;

TRUNCATE TABLE IF EXISTS STG_SHOPS;
COPY INTO STG_SHOPS FROM @s3_tcc_stage/shops.csv;

TRUNCATE TABLE IF EXISTS STG_ORDERS;
COPY INTO STG_ORDERS FROM @s3_tcc_stage/orders.csv;

TRUNCATE TABLE IF EXISTS STG_ORDER_POSITIONS;
COPY INTO STG_ORDER_POSITIONS FROM @s3_tcc_stage/order_positions.csv;

TRUNCATE TABLE IF EXISTS STG_CUSTOMERS;
COPY INTO STG_CUSTOMERS FROM @s3_tcc_stage/customers.csv;
